In [3]:
# 给定的二维列表
lst = [[0, 1], [1, 0], [1, 2], [2, 1], [2, 3], [3, 2], [3, 4], [4, 3], [4, 5], [5, 4], [5, 6], [6, 5], [6, 7], [7, 6], [7, 8], [8, 7], [8, 9], [9, 8]]

a = [[0,0], [0,1], [0,2],[0,3],[0,4],[0,5],[1,1],[1,2],[1,3],[1,4],[1,5],[2,2],[2,3],[2,4],[2,5],[3,3],[3,4],[3,5],[4,4],[4,5],[5,5]]

TypeError: unhashable type: 'list'

In [10]:
import torch
from torch_geometric.data import Data

data = Data(x=torch.randn(4, 16),
           edge_index=torch.tensor([[0, 1, 2, 3], [1, 0, 3, 2]]),
           edge_attr=torch.randn(4, 3),
           y=torch.randn(4, 3),
           )
data.num_node_types = 12
print(data.edge_index)

tensor([[0, 1, 2, 3],
        [1, 0, 3, 2]])


In [3]:
import torch
from torch_sparse import SparseTensor

# 示例用法
dense_matrix = torch.tensor([[0, 1, 0, 1],
                              [1, 0, 1, 0],
                              [0, 1, 0, 1],
                              [1, 0, 1, 0]])


print(dense_matrix)

sparse_matrix = SparseTensor.from_dense(dense_matrix)
print(sparse_matrix)

dense_matrix_converted = sparse_matrix.to_dense().view(-1)
print(len(dense_matrix_converted))

tensor([[0, 1, 0, 1],
        [1, 0, 1, 0],
        [0, 1, 0, 1],
        [1, 0, 1, 0]])
SparseTensor(row=tensor([0, 0, 1, 1, 2, 2, 3, 3]),
             col=tensor([1, 3, 0, 2, 1, 3, 0, 2]),
             val=tensor([1, 1, 1, 1, 1, 1, 1, 1]),
             size=(4, 4), nnz=8, density=50.00%)
16


In [21]:
import torch
from torch_geometric.data import Data, DataLoader

# 创建一些示例图数据
graph1 = Data(x=torch.randn(4, 16), edge_index=torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]]), name='ddd')
graph2 = Data(x=torch.randn(3, 16), edge_index=torch.tensor([[0, 1], [1, 2]]), name='eee')
graph3 = Data(x=torch.randn(2, 16), edge_index=torch.tensor([[0, 1], [1, 0]]), name='fff')

# 创建 DataLoader
dataloader = DataLoader([graph1, graph2, graph3], batch_size=2)

# 迭代批次
for batch_data in dataloader:
    # print(batch_data.keys())
    # print(batch_data.batch)
    # 获取批次中每个图的索引
    unique_batch_indices = torch.unique(batch_data.batch)
    print(unique_batch_indices)
    # 迭代并处理每个图
    for batch_index in unique_batch_indices:
        subgraph = batch_data.index_select(batch_index)
        print(subgraph)
        print(f"子图 {batch_index} 的节点特征：\n{subgraph[0].x}\n")

tensor([0, 1])
[Data(x=[4, 16], edge_index=[2, 4], name='ddd')]
子图 0 的节点特征：
tensor([[-1.0941,  0.5248,  0.0369, -0.4205,  0.6104, -0.6196, -0.4649, -1.3183,
          1.1503, -1.4818, -0.1798, -0.5130, -0.1696, -0.0919,  1.5649,  0.3439],
        [-0.0088, -0.7808, -0.8181, -0.7134,  1.5739,  0.2584,  1.2070,  0.2292,
         -0.5087, -0.2863, -0.5346, -0.1086,  0.0482, -1.9581,  0.1813, -1.4787],
        [-0.7656,  0.9060, -0.8840,  0.0875, -0.7424, -1.7161,  0.1466, -1.3477,
         -0.7912, -2.0520, -0.1750,  1.0111,  0.5479,  0.7827, -0.2881,  0.4188],
        [-1.0036, -0.8120, -1.2302, -1.0445,  1.8612, -0.0759,  0.3690, -0.3883,
         -0.1336,  0.3141, -0.0938, -0.4651, -0.0555,  1.0692, -1.0862,  1.0460]])

[Data(x=[3, 16], edge_index=[2, 2], name='eee')]
子图 1 的节点特征：
tensor([[-0.7634,  1.5982, -1.6123,  1.8558,  0.9032, -0.4893, -1.3870, -0.9298,
          1.1899,  0.6080,  0.6183, -0.6340,  0.0245, -0.6931,  0.8428, -0.9224],
        [ 1.0825,  1.4712,  0.2694, -0.0908,  