In [3]:
# 给定的二维列表
lst = [[0, 1], [1, 0], [1, 2], [2, 1], [2, 3], [3, 2], [3, 4], [4, 3], [4, 5], [5, 4], [5, 6], [6, 5], [6, 7], [7, 6], [7, 8], [8, 7], [8, 9], [9, 8]]

a = [[0,0], [0,1], [0,2],[0,3],[0,4],[0,5],[1,1],[1,2],[1,3],[1,4],[1,5],[2,2],[2,3],[2,4],[2,5],[3,3],[3,4],[3,5],[4,4],[4,5],[5,5]]

TypeError: unhashable type: 'list'

In [10]:
import torch
from torch_geometric.data import Data

data = Data(x=torch.randn(4, 16),
           edge_index=torch.tensor([[0, 1, 2, 3], [1, 0, 3, 2]]),
           edge_attr=torch.randn(4, 3),
           y=torch.randn(4, 3),
           )
data.num_node_types = 12
print(data.edge_index)

tensor([[0, 1, 2, 3],
        [1, 0, 3, 2]])


In [115]:
import scipy.sparse as sp
adjacency_matrix = [[0, 100.0, 0],
                              [1, 0, 2],
                              [0, -1, 0]]
tmp_coo = sp.coo_matrix(adjacency_matrix)
values = tmp_coo.data
print(tmp_coo)
print(tmp_coo.row)
print(tmp_coo.col)

  (0, 1)	100.0
  (1, 0)	1.0
  (1, 2)	2.0
  (2, 1)	-1.0
[0 1 1 2]
[1 0 2 1]


In [116]:
b = sp.coo_matrix((values, (tmp_coo.row, tmp_coo.col)))
print(b.todense())

[[  0. 100.   0.]
 [  1.   0.   2.]
 [  0.  -1.   0.]]


In [2]:
import torch
from torch_sparse import SparseTensor

# 示例用法
dense_matrix = torch.tensor([[0, 1, 0, 1],
                              [1, 0, 1, 0],
                              [0, 1, 0, 1],
                              [1, 0, 1, 0]])


print(dense_matrix)

sparse_matrix = SparseTensor.from_dense(dense_matrix)
print(sparse_matrix)

dense_matrix_converted = sparse_matrix.to_dense()
print(dense_matrix_converted)

tensor([[0, 1, 0, 1],
        [1, 0, 1, 0],
        [0, 1, 0, 1],
        [1, 0, 1, 0]])
SparseTensor(row=tensor([0, 0, 1, 1, 2, 2, 3, 3]),
             col=tensor([1, 3, 0, 2, 1, 3, 0, 2]),
             val=tensor([1, 1, 1, 1, 1, 1, 1, 1]),
             size=(4, 4), nnz=8, density=50.00%)
tensor([[0, 1, 0, 1],
        [1, 0, 1, 0],
        [0, 1, 0, 1],
        [1, 0, 1, 0]])
