In [2]:
from torch_geometric.datasets import Planetoid
import torch
from torch_geometric.data import Data
from torch_geometric.data import DataLoader

In [30]:
x = torch.tensor([[-1, 0, 1], [0, 1, 2]], dtype=torch.float)
y = torch.tensor([0, 1], dtype=torch.long)
 
edge_index = torch.tensor([[0, 1],
                           [1, 0]], dtype=torch.long)
dataset_list = []
for i in range(1):
    data = Data(x=x, edge_index=edge_index, y=y)
    dataset_list.append(data)

In [31]:
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

In [32]:
custom_dataset = CustomDataset(dataset_list)
custom_dataset[0]

Data(x=[2, 3], edge_index=[2, 2], y=[2])

In [33]:
dataloader = DataLoader(custom_dataset, batch_size=1, shuffle=True)

/home/btr/miniconda3/envs/llmsage/lib/python3.10/site-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


In [34]:
for batch in dataloader:
    print(batch.x)
    print(batch.y)

tensor([[-1.,  0.,  1.],
        [ 0.,  1.,  2.]])
tensor([0, 1])


In [37]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GCNConv
from torch_geometric.nn import SAGEConv

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = SAGEConv(3, 3, aggr='mean')
        self.conv2 = SAGEConv(3, 2, aggr='mean')

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = self.conv1(x, edge_index)
        print(x)
        # x = F.relu(x)
        # x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index)

        return x

In [41]:
model = Net()
optizer = torch.optim.SGD(model.parameters(), lr=0.01)
criterion = nn.CrossEntropyLoss()

model.train()
for epoch in range(10):
    for data in dataloader:
        optizer.zero_grad()
        output = model(data)
        loss = criterion(output, data.y)
        loss.backward()
        optizer.step()

tensor([[ 0.7795,  0.2021,  1.2306],
        [-0.3015,  1.3017, -0.3251]], grad_fn=<AddBackward0>)
tensor([[ 0.7867,  0.2033,  1.2294],
        [-0.3085,  1.3005, -0.3240]], grad_fn=<AddBackward0>)
tensor([[ 0.7939,  0.2043,  1.2283],
        [-0.3155,  1.2994, -0.3230]], grad_fn=<AddBackward0>)
tensor([[ 0.8010,  0.2053,  1.2273],
        [-0.3224,  1.2983, -0.3220]], grad_fn=<AddBackward0>)
tensor([[ 0.8080,  0.2062,  1.2264],
        [-0.3292,  1.2974, -0.3212]], grad_fn=<AddBackward0>)
tensor([[ 0.8150,  0.2071,  1.2256],
        [-0.3360,  1.2964, -0.3204]], grad_fn=<AddBackward0>)
tensor([[ 0.8219,  0.2079,  1.2248],
        [-0.3427,  1.2956, -0.3197]], grad_fn=<AddBackward0>)
tensor([[ 0.8287,  0.2087,  1.2242],
        [-0.3493,  1.2948, -0.3191]], grad_fn=<AddBackward0>)
tensor([[ 0.8354,  0.2093,  1.2236],
        [-0.3559,  1.2941, -0.3186]], grad_fn=<AddBackward0>)
tensor([[ 0.8421,  0.2100,  1.2230],
        [-0.3624,  1.2934, -0.3181]], grad_fn=<AddBackward0>)


In [1]:
a = [1,2,3]
b = [4,5,6]
a.extend(b)

21